services:
  - type: web
    name: attendance-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # or your actual start command
    pythonVersion: 3.10.12
