build:
  pythonVersion: 3.11.4
  # Optional: set a specific Poetry version if needed
  poetryVersion: 1.6.1

# Optional: define build command (if not using Poetry)
# buildCommand: "pip install -r requirements.txt"

start:
  command: "gunicorn app:app"
